import '@/assets/globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'omar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: any
}) {
  return (
    <html lang={params.lang} dir={params.lang === 'ar' ? 'rtl' : 'ltr'}>
      <body>
        <h1>omar</h1>
        {children}
      </body>
    </html>
  )
}
