'use client'

import '@/assets/globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { useEffect } from 'react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    console.log('hello from layout')
  }, [])

  return (
    <html lang="en">
      <body>
        <h1>omar</h1>
        {children}
      </body>
    </html>
  )
}
