import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <h1>from child layout</h1>
      {children}
    </div>
  )
}
